### ISSUE TITLE
Finding source of truth

### ISSUE THREAD

**Issue by dave2wave** [apache/tooling-docs#11]
The true source of truth for the public files that whimsy creates can be found by examining the details in this file: https://github.com/apache/whimsy/blob/master/repository.yml

For example:

```yaml
board:
    url: private/committers/board
    depth: empty
    files:
      - calendar.txt
      - committee-info.txt
      - committee-info.yaml
```

These three files are here: `svn co https://svn.apache.org/repos/private/committers/board`

```yaml
incubator-content:
    url: asf/incubator/public/trunk/content
    depth: empty
    files:
      - podlings.xml
```

This file is here: `svn co https://svn.apache.org/repos/asf/incubator/public/trunk/content`
